### ISSUE TITLE
本地部署后，注册 登录，填写个人信息页面，提交后，没反应

### ISSUE THREAD

**Issue by mmabluesky** [jobmission/oauth2-server#10]
rt ，

**Comment by mmabluesky** [comment]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by jobmission** [comment]
图片看不到呢

**Comment by jobmission** [comment]
因为是单点登录系统，所以登录后没有做更深层次的功能，需要更多的业务需要自己实现，你也可以把修改个人信息的功能删掉，登录后显示个简单的页面

**Comment by mmabluesky** [comment]
![image](https://user-images.githubusercontent.com/17948377/58923745-75de4300-8773-11e9-8048-515a18e9f05f.png)
这个页面怎么出来的

**Comment by mmabluesky** [comment]
![image](https://user-images.githubusercontent.com/17948377/58923780-9efed380-8773-11e9-8070-453d65f3caa8.png)
![image](https://user-images.githubusercontent.com/17948377/58923795-afaf4980-8773-11e9-8cc6-a152ee729fbf.png)

提交后没反应啊

**Comment by mmabluesky** [comment]
@jobmission 
java小白，求指教 ，以前弄c++的，临时拉来弄后台 ...

**Comment by jobmission** [comment]
用户管理页需要管理员权限登录，初始化sql里有一个账号zhangsan,
INSERT INTO user_account_entity (id, username, password, role, remarks)
VALUES (1, 'zhangsan', '$2a$10$gcrWom7ubcRaVD1.6ZIrIeJP0mtPLH5J9V/.8Qth59lZ4B/5HMq96', 'ROLE_SUPER', '测试明文:tgb.258'),
(2, 'lisi', '$2a$10$gcrWom7ubcRaVD1.6ZIrIeJP0mtPLH5J9V/.8Qth59lZ4B/5HMq96', 'ROLE_USER', '测试明文:tgb.258');

**Comment by mmabluesky** [comment]
![image](https://user-images.githubusercontent.com/17948377/58925079-d3c15980-8778-11e9-9bfd-8823c6b030e5.png)
难道我手法不对 ...

**Comment by jobmission** [comment]
初始密码，tgb.258
你输入的密码是什么，或者你把初始密码改掉

**Comment by mmabluesky** [comment]
搞定了
