### ISSUE TITLE
请问登录页中的/security_check这个是在哪个类中的

### ISSUE THREAD

**Issue by gmdqtd** [jobmission/oauth2-server#15]
请问登录页中的/security_check这个是在哪个类中的，一直没有找到。麻烦能告诉一下吗

**Comment by jobmission** [comment]
spring security 默认的登录验证地址是/j_spring_security_check，这个接口是内置的地址，但是是可以修改映射的，我修改成了/security_check；
修改方式是在  src/main/java/com/revengemission/sso/oauth2/server/config/SecurityConfiguration.java 这个类中修改.loginProcessingUrl("/security_check")；
修改后登录页面表单也需要修改post地址
