### ISSUE TITLE
如何部署集群？

### ISSUE THREAD

**Issue by liaostr** [jobmission/oauth2-server#27]
如何部署集群？

**Comment by jobmission** [comment]
这个项目只能算是学习使用，还未达到生产环境标准。
推荐更加产品化的keycloak，https://www.keycloak.org

**Comment by Hansin1997** [comment]
老哥可以看一下这个 项目：[https://github.com/dustlight-cn/auth](https://github.com/dustlight-cn/auth)

支持 K8S一键部署，欢迎提交 issue 和 pull request
