### ISSUE TITLE
/oauth/authorize接口的scope是必填字段吗？

### ISSUE THREAD

**Issue by antheatong** [jobmission/oauth2-server#31]
http://127.0.0.1:10380/oauth/authorize?client_id=123123&redirect_uri=http://123.com&response_type=code&state=pIvY63gJ
带上scope就成功，不带scope就失败。

status =500 INTERNAL_SERVER_ERROR,reason Internal Server Error;
exception =Cannot invoke "String.split(String)" because "scopes" is null;
uri =/oauth/authorize;
content Type =null;
request parameters ={"response_type":"[code]","redirect_uri":"[http://123.com]","state":"[pIvY63gJ]","client_id":"[123123]"}

java.lang.NullPointerException: Cannot invoke "String.split(String)" because "scopes" is null
	at com.revengemission.sso.oauth2.server.controller.OAuth2Controller.getAccessToken(OAuth2Controller.java:157) ~[classes!/:0.0.4-SNAPSHOT]
	at com.revengemission.sso.oauth2.server.controller.OAuth2Controller$$FastClassBySpringCGLIB$$65c4abd3.invoke(<generated>) ~[classes!/:0.0.4-SNAPSHOT]

**Comment by jobmission** [comment]
感谢使用，目前功能比较粗糙，有空会继续完善，推荐使用 https://github.com/spring-projects/spring-authorization-server

**Comment by antheatong** [comment]
好的，谢谢

**Comment by jobmission** [comment]
试试新版本
