### ISSUE TITLE
No redirect 

### ISSUE THREAD

**Issue by stutmf** [jobmission/oauth2-server#38]
hi. I followed the steps from README
`1. Get /oauth2/authorize?client_id=SampleClientId&response_type=code&redirect_uri=http://client.sso.com/login/oauth2/code/sso-loginscope=openid profile`
but the server fails with 999 and doesn’t redirect me. what do I do wrong?

**Comment by stutmf** [comment]
could be due to commented out AccessConfirmationController? How do I fix it?

**Comment by jobmission** [comment]
Update the code, delete relevant tables, and try again.
Attention! The project is not yet complete and is only used for learning and communication.
