### ISSUE TITLE
请问一下密码是多少

### ISSUE THREAD

**Issue by qingbuyaozaishuohehe** [jobmission/oauth2-server#7]

**Comment by jobmission** [comment]
参加 init.sql
INSERT INTO user_account_entity (id, username, password, role, remarks)
VALUES (1, 'zhangsan', '$2a$10$gcrWom7ubcRaVD1.6ZIrIeJP0mtPLH5J9V/.8Qth59lZ4B/5HMq96', 'ROLE_SUPER', '测试明文:tgb.258');
默认密码tgb.258
